<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Debug Mock;Release Mock</Configurations>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="$(Configuration.Contains('Mock'))">
    <DefineConstants>$(DefineConstants);MOCK</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" />
    <PackageReference Include="MessagePackAnalyzer">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Seeker\Soulseek.NET-master\src\Soulseek_Source.csproj" />
  </ItemGroup>

  <ItemGroup Condition="$(Configuration.Contains('Mock'))">
    <EmbeddedResource Include="DebugAssets\githublogo.png" />
  </ItemGroup>

</Project>
